# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='tracker.proto',
  package='com.mwicat.mxtrack.protobuf',
  serialized_pb='\n\rtracker.proto\x12\x1b\x63om.mwicat.mxtrack.protobuf\"E\n\x0bTrackerList\x12\x36\n\x08trackers\x18\x01 \x03(\x0b\x32$.com.mwicat.mxtrack.protobuf.Tracker\"\xa3\x01\n\x07Tracker\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x37\n\x04type\x18\x02 \x01(\x0e\x32).com.mwicat.mxtrack.protobuf.Tracker.Type\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0b\n\x03lat\x18\x04 \x01(\x01\x12\x0b\n\x03lng\x18\x05 \x01(\x01\x12\x0f\n\x07\x62\x61ttery\x18\x06 \x01(\x05\"\x1a\n\x04Type\x12\t\n\x05HUMAN\x10\x01\x12\x07\n\x03PET\x10\x02\x42\x31\n\x1b\x63om.mwicat.mxtrack.protobufB\x12TrackerMessageImpl')



_TRACKER_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='com.mwicat.mxtrack.protobuf.Tracker.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='HUMAN', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PET', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=255,
  serialized_end=281,
)


_TRACKERLIST = descriptor.Descriptor(
  name='TrackerList',
  full_name='com.mwicat.mxtrack.protobuf.TrackerList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='trackers', full_name='com.mwicat.mxtrack.protobuf.TrackerList.trackers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=115,
)


_TRACKER = descriptor.Descriptor(
  name='Tracker',
  full_name='com.mwicat.mxtrack.protobuf.Tracker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='com.mwicat.mxtrack.protobuf.Tracker.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='com.mwicat.mxtrack.protobuf.Tracker.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='com.mwicat.mxtrack.protobuf.Tracker.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lat', full_name='com.mwicat.mxtrack.protobuf.Tracker.lat', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lng', full_name='com.mwicat.mxtrack.protobuf.Tracker.lng', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='battery', full_name='com.mwicat.mxtrack.protobuf.Tracker.battery', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TRACKER_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=118,
  serialized_end=281,
)


_TRACKERLIST.fields_by_name['trackers'].message_type = _TRACKER
_TRACKER.fields_by_name['type'].enum_type = _TRACKER_TYPE
_TRACKER_TYPE.containing_type = _TRACKER;

class TrackerList(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKERLIST
  
  # @@protoc_insertion_point(class_scope:com.mwicat.mxtrack.protobuf.TrackerList)

class Tracker(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRACKER
  
  # @@protoc_insertion_point(class_scope:com.mwicat.mxtrack.protobuf.Tracker)

# @@protoc_insertion_point(module_scope)
